[package]
name = "xfg-stark"
version = "0.1.0"
edition = "2021"
authors = ["XFG STARK Team"]
description = "XFG STARK Proof Implementation"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
bincode = "1.3"
sha2 = "0.10"
rand = "0.8"
